### ISSUE TITLE
time change

### ISSUE THREAD

**Issue by fmeulen** [JuliaDiffusionBayes/GuidedProposals.jl#2]
The doc is incorrect for `standard_guid_prop_time_transf(tt)`. 

the transformation should be 
t0 + (t-t0) (2-(t-t0)/(T-t0))
as is (correctly) implemented

**Comment by mmider** [comment]
I can't see the problem [in the docs](https://juliadiffusionbayes.github.io/GuidedProposals.jl/dev/module_index/#GuidedProposals.standard_guid_prop_time_transf-Tuple{Any}). It seems to me that the implementation and the docs agree... What should be changed?

**Comment by fmeulen** [comment]
the “2-“ should not be in the numerator (Just plug in t=T, then one should get T, right?)


---
Frank van der Meulen
Delft University of Technology
http://dutiosb.twi.tudelft.nl/~meulen/


On 26 Jun 2020, at 15.01, Marcin Mider <notifications@github.com<mailto:notifications@github.com>> wrote:



I can't see the problem in the docs<https://urldefense.proofpoint.com/v2/url?u=https-3A__juliadiffusionbayes.github.io_GuidedProposals.jl_dev_module-5Findex_-23GuidedProposals.standard-5Fguid-5Fprop-5Ftime-5Ftransf-2DTuple-257BAny-257D&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=7iF-JNHl-g2k0SDAFdfpFNwTGT5g4T8E90C3u4ODfF8&m=4vAe-zGs6jfQphNl5qgnVktTiWiQc6KQmtkcTNij6Tc&s=aqqxvntf4KFJv9NbRoynelgUkgUa3M0Yb0q4vyFCkAs&e=>. It seems to me that the implementation and the docs agree... What should be changed?

**Comment by mmider** [comment]
Thanks, I realized right after I sent a message and I edited my response accordingly on github. The edits are no longer sent to email.

**Comment by mmider** [comment]
56477ad
